Error from server (AlreadyExists): pods "udacitymicro" already exists
NAME           READY   STATUS    RESTARTS   AGE
udacitymicro   1/1     Running   0          41m
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000
* Serving Flask app "app" (lazy loading)
* Environment: production
WARNING: Do not use the development server in a production environment.
Use a production WSGI server instead.
* Debug mode: on
* Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
* Restarting with stat
* Debugger is active!
* Debugger PIN: 230-565-583
* Detected change in '/app/app.py', reloading
* Restarting with stat
* Debugger is active!
* Debugger PIN: 230-565-583
[2022-07-12 19:52:11,489] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 150.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-07-12 19:52:11,557] INFO in app: Inference payload DataFrame:
CHAS RM TAX PTRATIO B LSTAT
0 0 6.575 296.0 150.3 396.9 4.98
[2022-07-12 19:52:11,574] INFO in app: Scaling Payload:
CHAS RM TAX PTRATIO B LSTAT
0 0 6.575 296.0 150.3 396.9 4.98
[2022-07-12 19:52:11,595] INFO in app: Prediction value
[20.35373177134412]
127.0.0.1 - - [12/Jul/2022 19:52:11] "POST /predict HTTP/1.1" 200 -